### ISSUE TITLE
find_nests() error

### ISSUE THREAD

**Issue by teaguescott** [picardis/nestR#17]
Hi, I'm trying to get going on analyzing recursive movement in my dataset.

I have my data formatted correctly with _burst_ (character), _date_ (POSIXct, same format as in vignette), _long_ (numeric), and _lat_ (numeric).

When I try and run the find_nests() function on the dataset, with _sea_start_ & _sea_end_ (character), _nest_cycle_ (numeric), and _buffer_ (numeric), I get this error:

`Error: Expecting a single value: [extent=2].`

What is bringing up this error?

Thanks,

Teague

**Comment by picardis** [comment]
Hi, 

Very sorry for responding so late -- I had notifications off. If you still need help, could you send a reproducible example (a snippet of data + your current code)? I'll try to reproduce the error on my computer and troubleshoot it.

**Comment by bsmity13** [comment]
For anyone else troubleshooting a similar issue, sharing the results of `traceback()` can help pinpoint the source of the error. And of course, a reproducible example is the most helpful for troubleshooting.
