### ISSUE TITLE
Failure to identify consecutive nest site in same season

### ISSUE THREAD

**Issue by coverton-usgs** [picardis/nestR#19]
Many thanks for your time,

I have a bird displaying admittedly unusual behaviors, wherein it appears a nest site was abandoned 2 days into the 4-6 day egg laying period but a new nest was started immediately after and incubated for 7 subsequent days (100% of ~half hourly locations).  Unfortunately at this point, the transmitter suffered a power failure and only obtained 3 locations in the subsequent 18 days (all at the 2nd nest site).  

My guess, is that the intermittent data is responsible for the failure to identify the second nest site.  But it isn't clear to me why this would occur given the settings used in `find_nests()`  Even if the days following the battery failure do not meet the `min_pts = 4` criteria, the first 6 days do meet that criteria.

For reference: here is the first nest site (lower right of the screen): 
![image](https://user-images.githubusercontent.com/43579258/179423937-4ce21bee-2b80-4f14-8f46-0fb7206c5baf.png)

And here is the second (upper left of the screen):
![image](https://user-images.githubusercontent.com/43579258/179423954-048c0f52-a85e-474a-b8b8-081cc4746d6f.png)

Several settings were used to identify the nest.
Each attempt identified ONLY the first 2 day nesting/egg-laying period in the lower left of the graphics above: 
`find_nests(gps_data = nesting_period_locations_confirmed_birds,
                    sea_start = "05-01",
                    sea_end = "08-01",
                    nest_cycle = 33,
                    buffer = 150,
                    min_pts = 4,
                    min_d_fix = 12,
                    min_consec = 5,
                    min_top_att = 80,
                    min_days_att = 80,
                    discard_overlapping = FALSE)`

And the data is provided here:
[interrupted_laying_2021.csv](https://github.com/picardis/nestR/files/9128489/interrupted_laying_2021.csv)

**Comment by coverton-usgs** [comment]
You're brilliant, thank you!  In practice I'll probably have to limit the input data when we have transmitter failures and intermittent activity, but this is a great verification for how to get it to work properly.

**Comment by picardis** [comment]
Awesome! Glad I could help!
