### ISSUE TITLE
final data table

### ISSUE THREAD

**Issue by Kruckenberg-IWWR** [picardis/nestR#21]
Hi, we used the NestR via Moveapps and now I`m a bit comfused what the data columns of the final table showing. Could you give me an advise how to interpret / use the results? /HK

**Comment by bsmity13** [comment]
Hi. Working through the package vignette might help understanding the possible outputs. See issue #22 for a link to a PDF of the vignette.

I haven't used the Moveapp, but it seems to just run `find_nests()`. In that case, just Part I of the vignette will be most informative for you. For statistical inference on nest survival, you'll want to look into Part II of the vignette.
