### ISSUE TITLE
Error in find_nests() 

### ISSUE THREAD

**Issue by estella-sage** [picardis/nestR#25]
hi,I tried to use the function find_nests(),but following error occurred,and I  still got the same problem when I used the dataset woodstorks in nestR.

Error:
! Can't subset `.data` outside of a data mask context.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by ckgulick** [comment]
I also ran into this issue. When I ran 'rlang::last_trace()', the following returned: 
<error/rlang_error>
Error:
! Can't subset `.data` outside of a data mask context.
---
Backtrace:
     ▆
  1. ├─nestR::find_nests(...)
  2. │ └─... %>% dplyr::arrange(dplyr::desc(.data$tot_vis))
  3. ├─dplyr::arrange(., dplyr::desc(.data$tot_vis))
  4. ├─dplyr::select(...)
  5. ├─dplyr::mutate(., burst = burst_id)
  6. ├─dplyr::mutate(...)
  7. ├─dplyr::mutate(...)
  8. ├─dplyr::left_join(...)
  9. ├─dplyr:::left_join.data.frame(...)
 10. │ └─dplyr::auto_copy(x, y, copy = copy)
 11. │   ├─dplyr::same_src(x, y)
 12. │   └─dplyr:::same_src.data.frame(x, y)
 13. │     └─base::is.data.frame(y)
 14. ├─dplyr::select(.data$dat, .data$loc_id, .data$long, .data$lat)
 15. ├─dat
 16. └─rlang:::`$.rlang_fake_data_pronoun`(.data, dat)
 17.   └─rlang:::stop_fake_data_subset(call)
 18.     └─rlang::abort(...)

**Comment by picardis** [comment]
Fixed! Please reinstall the package and it should run smoothly now.

**Comment by picardis** [comment]
Fixed!
